Repository OpenSourceRaidGuild/SlickGrid, pull requests merged in 2021-04, with the labels that each got.

#7 fix(auto-tooltips): converted auto-tooltip plugin + some ts defaults
  .gitignore
  @lib/lib/firebugx.js
  @lib/plugins/slick.autotooltips.js
  @types/lib/firebugx.d.ts
  @types/plugins/slick.autotooltips.d.ts
  cypress/support/commands.ts
  examples/example-autotooltips.html
  lib/firebugx.ts
  package-lock.json
  package.json
  plugins/slick.autotooltips.ts
  tsconfig.build.json
  tsconfig.json
Labels: Difficulty: Hardmode :mountain_bicyclist:, Items: Rare, Items: Uncommon, Quest: Main, Raid: Boss, Type: Refactor

#6 migrate slick.formatters, add JQuery type definitions and tsconfig changes
  @scripts/lib/firebugx.js
  @scripts/plugins/slick.autotooltips.js
  @scripts/slick.formatters.js
  @types/slick.formatters.d.ts
  SlickGrid.d.ts
  cypress/integration/example-checkbox-header-row.spec.ts
  examples/example-autocomplete-editor.html
  examples/example-autotooltips.html
  examples/example-checkbox-row-select.html
  examples/example-composite-editor-item-details.html
  examples/example-composite-editor-modal-dialog.html
  examples/example-draggable-grouping.html
  examples/example-dynamic-filtered-with-jquery-tabs.html
  examples/example-excel-compatible-spreadsheet-dataview.html
  examples/example-excel-compatible-spreadsheet.html
  examples/example-frozen-columns-and-rows.html
  examples/example-frozen-columns-large.html
  examples/example-frozen-columns-tabs.html
  examples/example-frozen-columns.html
  examples/example-frozen-row-reordering.html
  examples/example-frozen-rows.html
  examples/example-grouping-checkbox-row-select.html
  examples/example-grouping-groupcolumn.html
  examples/example-grouping.html
  examples/example-multiselect-editor.html
  examples/example-optimizing-dataview.html
  examples/example-optimizing-updates.html
  examples/example-plugin-contextmenu.html
  examples/example-row-detail-selection-and-move.html
  examples/example-select2-editor.html
  examples/example-select2-multiselect-editor.html
  examples/example-size-to-content.html
  examples/example16-row-detail.html
  examples/example17-row-detail-many-columns.html
  examples/example2-formatters-event.html
  examples/example2-formatters.html
  examples/example3-editing.html
  examples/example3b-editing-with-undo.html
  examples/example4-model.html
  examples/example5-collapsing.html
  examples/example9-row-reordering-simple.html
  examples/example9-row-reordering.html
  slick.formatters.js
  slick.formatters.ts
  tests/init benchmark.html
  tests/scrolling benchmark raf.html
  tests/scrolling benchmarks.html
  tests/test-4-rows-paging.html
  tsconfig.json
Labels: Difficulty: Hardmode :mountain_bicyclist:, Items: Rare, Items: Uncommon, Quest: Main, Raid: Boss, Status: In Progress 🚧, Type: Refactor, Type: Toolchain

#13 migrate slick.remotemodel-yahoo to ts
  @scripts/slick.remotemodel-yahoo.js
  @types/slick.remotemodel-yahoo.d.ts
  examples/example6-ajax-loading-yahoo.html
  slick.remotemodel-yahoo.js
  slick.remotemodel-yahoo.ts
Labels: Difficulty: Hardmode :mountain_bicyclist:, Quest: Main, Raid: Boss, Status: Completed, Type: Refactor

#41 ts-conversion: cellRangeDecorator (plugin)
  @scripts/plugins/slick.cellrangedecorator.js
  @types/plugins/slick.cellrangedecorator.d.ts
  examples/example-autocomplete-editor.html
  examples/example-checkbox-row-select.html
  examples/example-colspan.html
  examples/example-draggable-grouping.html
  examples/example-excel-compatible-spreadsheet-dataview.html
  examples/example-excel-compatible-spreadsheet.html
  examples/example-frozen-columns-and-rows-spreadsheet.html
  examples/example-grouping-checkbox-row-select.html
  examples/example-grouping-groupcolumn.html
  examples/example-grouping.html
  examples/example-multiselect-editor.html
  examples/example-select2-editor.html
  examples/example-select2-multiselect-editor.html
  examples/example-spreadsheet.html
  examples/example3-editing.html
  package-lock.json
  package.json
  plugins/slick.cellrangedecorator.ts
Labels: Difficulty: Heroic, Quest: Main, Raid: Boss, Type: Refactor

#20 fix: AutoTooltips ts conversion update
  @types/plugins/slick.autotooltips.d.ts
  plugins/slick.autotooltips.ts
Labels: Difficulty: Beginner :nerd_face:, Quest: Main, Raid: Boss, Type: Refactor
